
[e_ca_too_few_beers]
# This MUST be set to the number of bottles of beer that were on the signing CAs wall at the time of issuance.
BottlesOfBeerOnTheWall = 0
Cosigner = """
-----BEGIN CERTIFICATE-----
MIIDAzCCAmygAwIBAQIETLCaTzANBgkqhkiG9w0BAQQFADCBuDELMAkGA1UEBhMC
SUwxCzAJBgNVBAgTAklMMRUwEwYDVQQHEwxEZW1vIEFkZHJlc3MxDjAMBgNVBBET
BTEyMzQ1MRgwFgYDVQQUEw8oMDAwLTApIDAwMDAwMDAxHDAaBgkqhkiG9w0BCQEW
DURlbW9AZGVtby5jb20xEjAQBgNVBAoTCURlbW8gSW5jLjENMAsGA1UECxMERGVt
bzEaMBgGA1UEAxMRdHlwby5zZ2RwYmVsbC5jb20wHhcNMTIwNDI3MDAwMDAwWhcN
MjIwNDI3MDUwMDAwWjCBuDELMAkGA1UEBhMCSUwxCzAJBgNVBAgTAklMMRUwEwYD
VQQHEwxEZW1vIEFkZHJlc3MxDjAMBgNVBBETBTEyMzQ1MRgwFgYDVQQUEw8oMDAw
LTApIDAwMDAwMDAxHDAaBgkqhkiG9w0BCQEWDURlbW9AZGVtby5jb20xEjAQBgNV
BAoTCURlbW8gSW5jLjENMAsGA1UECxMERGVtbzEaMBgGA1UEAxMRdHlwby5zZ2Rw
YmVsbC5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKyiNTxe6BhY3Aau
rbflrC8M6DoFcdbhgIZnQq8Mf7Jiogxg0k0dawCHglBUzMuszsvTWIAxJu/hyA2W
oLLqNZglnWNjNEAywKtizq0ErePKG3pphXErKWIv7ZKPyWbdqQBxkrQ9sQPIlPBB
Mu8PGjMpcFqhYH1QijYemWHiu0ezAgMBAAGBCwNraXNoa3VzaGloggsDa2lzaGt1
c2hpaDANBgkqhkiG9w0BAQQFAAOBgQCN1DUWa976qhQV3JQ6YF6jNJEepYKpqzLE
tQ7fZgh36wJR6kWtCETxQwKnowWPggxUwx27r4fRHrFa1WxUCGNlMKjpcEw+EK0Y
1WGePq4919wMyMdaiz6vhNVbnOhKwEcgUKrYlksDMNKPUlDUjfm/w+HdPqMxsnA+
S5jc+5/gQg==
-----END CERTIFICATE-----
"""

[e_ca_too_few_beers.i_spy_with_my_little_eye]
# Any number of descriptions that are valid for the subject.
Descriptions = ["larger than a bread box", "smaller than a barn"]
Subject = "A car"

[w_web_pki_cert]
# Indicates that the certificate is intended for the Web PKI.
is_web_pki = false

